// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: proto/decompopb.proto

package decomp

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DecoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *DecoRequest) Reset() {
	*x = DecoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_decompopb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoRequest) ProtoMessage() {}

func (x *DecoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decompopb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoRequest.ProtoReflect.Descriptor instead.
func (*DecoRequest) Descriptor() ([]byte, []int) {
	return file_proto_decompopb_proto_rawDescGZIP(), []int{0}
}

func (x *DecoRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type DecoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DecoResponse) Reset() {
	*x = DecoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_decompopb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoResponse) ProtoMessage() {}

func (x *DecoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decompopb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoResponse.ProtoReflect.Descriptor instead.
func (*DecoResponse) Descriptor() ([]byte, []int) {
	return file_proto_decompopb_proto_rawDescGZIP(), []int{1}
}

func (x *DecoResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_decompopb_proto protoreflect.FileDescriptor

var file_proto_decompopb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x70,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a,
	0x0c, 0x44, 0x65, 0x63, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x59, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x44, 0x65, 0x63, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_decompopb_proto_rawDescOnce sync.Once
	file_proto_decompopb_proto_rawDescData = file_proto_decompopb_proto_rawDesc
)

func file_proto_decompopb_proto_rawDescGZIP() []byte {
	file_proto_decompopb_proto_rawDescOnce.Do(func() {
		file_proto_decompopb_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_decompopb_proto_rawDescData)
	})
	return file_proto_decompopb_proto_rawDescData
}

var file_proto_decompopb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_decompopb_proto_goTypes = []interface{}{
	(*DecoRequest)(nil),  // 0: decomposition.DecoRequest
	(*DecoResponse)(nil), // 1: decomposition.DecoResponse
}
var file_proto_decompopb_proto_depIdxs = []int32{
	0, // 0: decomposition.DecoService.Decomposite:input_type -> decomposition.DecoRequest
	1, // 1: decomposition.DecoService.Decomposite:output_type -> decomposition.DecoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_decompopb_proto_init() }
func file_proto_decompopb_proto_init() {
	if File_proto_decompopb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_decompopb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_decompopb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_decompopb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_decompopb_proto_goTypes,
		DependencyIndexes: file_proto_decompopb_proto_depIdxs,
		MessageInfos:      file_proto_decompopb_proto_msgTypes,
	}.Build()
	File_proto_decompopb_proto = out.File
	file_proto_decompopb_proto_rawDesc = nil
	file_proto_decompopb_proto_goTypes = nil
	file_proto_decompopb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DecoServiceClient is the client API for DecoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DecoServiceClient interface {
	Decomposite(ctx context.Context, in *DecoRequest, opts ...grpc.CallOption) (DecoService_DecompositeClient, error)
}

type decoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecoServiceClient(cc grpc.ClientConnInterface) DecoServiceClient {
	return &decoServiceClient{cc}
}

func (c *decoServiceClient) Decomposite(ctx context.Context, in *DecoRequest, opts ...grpc.CallOption) (DecoService_DecompositeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DecoService_serviceDesc.Streams[0], "/decomposition.DecoService/Decomposite", opts...)
	if err != nil {
		return nil, err
	}
	x := &decoServiceDecompositeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DecoService_DecompositeClient interface {
	Recv() (*DecoResponse, error)
	grpc.ClientStream
}

type decoServiceDecompositeClient struct {
	grpc.ClientStream
}

func (x *decoServiceDecompositeClient) Recv() (*DecoResponse, error) {
	m := new(DecoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DecoServiceServer is the server API for DecoService service.
type DecoServiceServer interface {
	Decomposite(*DecoRequest, DecoService_DecompositeServer) error
}

// UnimplementedDecoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDecoServiceServer struct {
}

func (*UnimplementedDecoServiceServer) Decomposite(*DecoRequest, DecoService_DecompositeServer) error {
	return status.Errorf(codes.Unimplemented, "method Decomposite not implemented")
}

func RegisterDecoServiceServer(s *grpc.Server, srv DecoServiceServer) {
	s.RegisterService(&_DecoService_serviceDesc, srv)
}

func _DecoService_Decomposite_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DecoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecoServiceServer).Decomposite(m, &decoServiceDecompositeServer{stream})
}

type DecoService_DecompositeServer interface {
	Send(*DecoResponse) error
	grpc.ServerStream
}

type decoServiceDecompositeServer struct {
	grpc.ServerStream
}

func (x *decoServiceDecompositeServer) Send(m *DecoResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DecoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "decomposition.DecoService",
	HandlerType: (*DecoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Decomposite",
			Handler:       _DecoService_Decomposite_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/decompopb.proto",
}
